### ISSUE TITLE
Watch List

### ISSUE THREAD

**Issue by cliffordsnow** [osmbe/osm-welcome-belgium#32]
OSMCha has a watch list flag to add users to your watch list. Might be interesting to pick that information up. I've only added a few new users to a watch list, but have found it saves me from worrying about what they may do in the future. 

This can easily wait since OSMCha provides the feature now.

**Comment by jbelien** [comment]
If I understand correctly your request, you want to see on the Welcome Tool if a mapper is on your personal watchlist.

I can't seem to find a way to get that information from OSMCha API (see https://osmcha.org/api-docs/#operations-users-users_read) but I'm probably missing something (ping @willemarcel).

That would also require to store your personal OSMCha API Token in your account in the Welcome Tool.
This is not an issue but it make the user management a bit more complex (it is **really** basic now since it stores only the username and avatar URL when you login with osm.org OAuth2).

**Comment by joostschouppe** [comment]
If anything, I think the flow in the other direction would be useful:
- you review a new mapper
- you think: "this is fishy"
- you say: "I want to be informed if this mapper does something new"

Once you use this tool, it is unlikely that you would put a mapper on your watchlist BEFORE they show up in your "to welcome" list.

**Comment by jbelien** [comment]
Yes, that would indeed make sense.
But for now I don't see any way to automate that action from the Welcome Tool, the API doesn't seem to provide that.

**Comment by cliffordsnow** [comment]
I often wait a couple of days to see before reviewing. There haven't been many but a few have been flagged before I go to welcome them. But I agree that @joostschouppe suggestion of going the other way makes more sense.
