### ISSUE TITLE
Changeset count differs

### ISSUE THREAD

**Issue by angoca** [osmbe/osm-welcome-belgium#442]
In the list of users per area, the quantity of changes seems to be the current one.
However, once I have sent a welcome message, the quantity of changesets remains the same in the user view.

This is an example:

* User Lolj has 62 changeset currently - https://welcome.osm.be/bogota/list/2021/11
* However, in the user view I only see 2 - https://welcome.osm.be/bogota/mapper/14546644

Is this normal?

**Comment by jbelien** [comment]
I indeed wouldn't call it "normal" but it's not a bug either.

It's due to the fact that the process keeps updating the user information details (to detect a change in the username, for instance) including the number of changesets made by that user.
But I only fetch the changeset details for the changesets created the day that user contributed the first time.

I think that's useful because it allows you to know that that user kept mapping since its first contribution. That user basically created 60 new changesets since its first contribution.
