### ISSUE TITLE
An exception occurred while executing a query: SQLSTATE[HY000]: General error: 8 attempt to write a readonly database

### ISSUE THREAD

**Issue by mcliquid** [osmbe/osm-welcome-belgium#776]
URL: https://welcome.osm.be/mapper/17388754?welcome=1

![An-exception-occurred-while-executing-a-query-SQLSTATE-HY000-General-error-8-attempt-to-write-a-readonly-database-500-Internal-Server-Error-](https://user-images.githubusercontent.com/3351668/198869520-f226cf0b-b73c-4c45-b0b3-c808bf1bb569.png)

**Comment by jbelien** [comment]
Thanks @mcliquid !
Sorry about this, it's now fixed!

**Comment by mcliquid** [comment]
@jbelien Thanks for the fix! Can it be that the database in general has a problem? I currently get almost daily new entries from users who I have already written to but then appear in the tool again as new. As if my changes are not saved.

**Comment by jbelien** [comment]
> Can it be that the database in general has a problem?
> I currently get almost daily new entries from users who I have already written to but then appear in the tool again as new. As if my changes are not saved.

A few weeks ago I migrated the OSM Welcome Tool to Digital Ocean App Platform.
But performances were really bad so I decided to go back to the initial setup (OSMBE VM).
Unfortunately I couldn't recuperate the changes made since the migration and you indeed have lost data.
You can follow this here: https://github.com/osmbe/community_planning/issues/41

Sorry for the inconvenience.
Good news: I've decided NOT to migrate OSM Welcome Tool in the end so these issues won't happen again.
