### ISSUE TITLE
Daily update not seen on country list

### ISSUE THREAD

**Issue by Jakkajakka** [osmbe/osm-welcome-belgium#800]
Today 15 nov 2022
![afbeelding](https://user-images.githubusercontent.com/11509181/201883907-8d3ff6af-d80b-4f4b-8a3e-a8e9d8191cc9.png)
last memeber seen on page 
![afbeelding](https://user-images.githubusercontent.com/11509181/201884084-1e0e19bb-673e-4b14-9fc7-8f255d9389ef.png)

**Comment by jbelien** [comment]
It happens from time to time.
I believe it's due to the fact that there are too many new mappers.
The request to get the users details is truncated (see below) and so the update is failing.

I'll fix it!

`https://api.openstreetmap.org/api/0.6/users.json?users=15453288%2C11308911%2C2999637%2C17466727%2C2999637%2C2999637%2C17684318%2C1848516%2C2677980%2C2677980%2C2677980%2C2677980%2C2677980%2C2677980%2C2677980%2C9054993%2C3047982%2C3047982%2C3047982%2C3047982%2C3047982%2C3047982%2C11308911%2C3047982%2C11308911%2C16465822%2C16465822%2C16465822%2C616463%2C11308911%2C11308911%2C6242403%2C11308911%2C16580197%2C16580197%2C11308911%2C11308911%2C11308911%2C16580197%2C11308911%2C11308911%2C11308911%2C17544843%2C17544843%2C673082%2C9054993%2C9054993%2C16675220%2C9054993%2C9054993%2C2692969%2C11308911%2C11308911%2C11308911%2C17673809%2C11308911%2C17676984%2C11308911%2C11308911%2C11308911%2C11308911%2C17676417%2C17608478%2C15328970%2C12167071%2C11308911%2C11308911%2C11308911%2C16363361%2C16363361%2C11308911%2C16363361%2C16363361%2C16363361%2C16363361%2C16363361%2C16363361%2C16363361%2C17607741%2C11308911%2C11308911%2C11308911%2C17544843%2C17544843%2C1246002%2C11308911%2C16088041%2C1246002%2C17544843%2C11308911%2C17668690%2C17668690%2C15453288%2C1875164%2C17531424%2C1875164%2C12875178%2C2054200%2C2054200%2C2054200%2C11308911%2C17669029%2C3588849%2C3588849%2C8268626%2C17669286%2C11308911%2C17669286%2C9343311%2C17669285%2C17669285%2C17669286%2C17669285%2C17669285%2C11308911%2C17669286%2C17669285%2C11308911%2C11308911%2C11308911%2C17669136%2C11308911%2C17668690%2C17277771%2C11308911%2C16839708%2C10061158%2C17277771%2C16839708%2C17607678%2C17646522%2C17646522%2C17646522%2C511977%2C511977%2C511977%2C16363361%2C16363361%2C16363361%2C16363361%2C16363361%2C511977%2C511977%2C17666432%2C1414376%2C17661476%2C17661476%2C17661476%2C17661476%2C17661476%2C17661476%2C17661476%2C17659174%2C17661451%2C17660348%2C9054993%2C17660969%2C9296953%2C17660348%2C6290466%2C17660348%2C17660348%2C6290466%2C2999637%2C16580197%2C15663461%2C16678278%2C1414376%2C11508277%2C15663461%2C15663461%2C15663461%2C11472160%2C11472160%2C11472160%2C11202303%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C17646522%2C17646522%2C4459690%2C17646522%2C17646522%2C16919215%2C17277771%2C14821227%2C14821227%2C907775%2C17650194%2C16919215%2C14821227%2C17650194%2C17650194%2C17650194%2C17650194%2C17650194%2C15211948%2C13956167%2C13956167%2C13956167%2C13956167%2C12526774%2C11696036%2C16931496%2C17647685%2C16931496%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C17584214%2C1246002%2C1246002%2C1246002%2C9054993%2C16937838%2C10312776%2C17646522%2C17646206%2C9054993%2C9054993%2C17646206%2C16456565%2C10282777%2C10282777%2C17645020%2C17544843%2C17544843%2C10282777%2C10282777%2C10282777%2C13991289%2C17643089%2C17643116%2C14133178%2C14133178%2C14133178%2C1413`

**Comment by jbelien** [comment]
Might also be due to a user that has deleted his/her account meanwhile.

**Comment by jbelien** [comment]
Fixed in #801
