### ISSUE TITLE
removing Panama region

### ISSUE THREAD

**Issue by mfrasca** [osmbe/osm-welcome-belgium#950]
I've been the only one using this tool, I lost interest in the community building, and nobody has been willing to take this task over from me. I suggest removal.

**Comment by jbelien** [comment]
Hello @mfrasca ,

Sorry to hear that but no worries, it doesn't cost anything to keep Panama in the tool even though no one is "taking care of it" (it's - unfortunately - the case for several regions).

That being said, if you prefer to remove Panama (whatever the reason is), I'll of course remove it.

**Comment by mfrasca** [comment]
when I opened the issue to have this included in the welcome tool, I must say, I did not (manage to) involve other local people. now the community officially split, and the "other half" appropriated accounts like osmpanama / openstreetmappanama on various social platforms. I think that it's confusing if this welcome space is around, and not managed by osmpanama, which, whatever that might be, it is definitely not me. you may keep this in place, awaiting for osmpanama to adopt it, or you may close it until osmpanama decides to file a new request.

**Comment by jbelien** [comment]
Yes, it's definitely not easy to motivate people to do this repetitive task to welcome new mappers.

I suggest we keep Panama in the tool just in case.

Thank you for having taken care of it for all this time!
